### ISSUE TITLE
Print Bar Codes from the Checklist view is Slow

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#37]
Aerica at Caldwel complained of the speed of the Print Bar Codes.

**Comment by Cllyde** [comment]
Is this a new issue from recent changes? If it isn't then I'm not sure it could be sped up at all.
It looks like the reason it is slow is because it uses the iDocListener service to create a connection to the barcode printer, and it takes time for the communication from idoc to the listener to the printer. I don't really see any way to speed it up.

**Comment by rwieseler** [comment]
The Selection of Bar codes is slow, also the time to pull up the screen takes time as well.

**Comment by Cllyde** [comment]
Changed to an ASP gridview instead of the devexpress gridview and it is a lot faster now.
