### ISSUE TITLE
Modify Existing Document Image Conversion to iDoc executable

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#44]
Review the code for this executable and add the ablity to add Link Types to certain Document Image Document Types.

**Comment by Cllyde** [comment]
I've changed the way the program logs to the "console" textbox, so that instead of writing a new line for every line in the bimage.txt file, it will write one line every 25 lines it processes just to let the user know what line it is on, and it will write any errors to the console.
Writing to the console for every line was taking up a LOT of resources, because every time a new line is written, a new string is created, and the memory for the new string has to be allocated. The size of the string continues to grow, so it gets slower and slower the more logging that is done. This stackoverflow.com answer gives some calculations at just how much memory allocation happens http://stackoverflow.com/a/5491564/1804496.
