### ISSUE TITLE
Checklist Explorer displays Doc Types only first 10 entries display in Red for Tech Exception

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#52]

**Comment by Cllyde** [comment]
Datatables paging preventing red "Technical Exception" text from being red.

**Comment by Cllyde** [comment]
Fixed this by using the datatables parameter [fnDrawCallback](http://datatables.net/usage/callbacks#fnDrawCallback) when the datatable is created, so that each time the page changes and the table is redrawn, it will check for "Technical Exception" and if it's found, it will change the font color to red.
