### ISSUE TITLE
Deleting CIF Level Document Types

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#67]
It is difficult to delete CIF Level Document Types, First you have to remove the CIF number from the Document Type then find all the linked Checklist that have that Document Type.  Go to those checklists and remove the Document Types.

**Comment by Cllyde** [comment]
I've changed the way removing a document type from a checklist works, so that if it had a CIF number, it will delete all the ChecklistLinks for that document type, and set it's deleted flag to true.

This will let a user delete a CIF document type from any checklist it is linked to, without having to go to the other checklists it was linked to and remove it from those as well.
